// ═══════════════════════════════════════════════════════════════
//  STOCK DATABASE — 260+ Companies (India NSE/BSE + US Markets)
// ═══════════════════════════════════════════════════════════════

export const STOCKS = [
  // ── INDIA: NIFTY 50 ──────────────────────────────────────────
  { symbol:"RELIANCE",  name:"Reliance Industries Ltd",      sector:"Energy",         base:2891, color:"#FF6B35", logo:"🛢️",  exchange:"NSE", currency:"₹" },
  { symbol:"TCS",       name:"Tata Consultancy Services",    sector:"IT",             base:3824, color:"#007AFF", logo:"💻",  exchange:"NSE", currency:"₹" },
  { symbol:"HDFCBANK",  name:"HDFC Bank Ltd",                sector:"Banking",        base:1654, color:"#30D158", logo:"🏦",  exchange:"NSE", currency:"₹" },
  { symbol:"INFY",      name:"Infosys Ltd",                  sector:"IT",             base:1482, color:"#5856D6", logo:"🖥️",  exchange:"NSE", currency:"₹" },
  { symbol:"HINDUNILVR",name:"Hindustan Unilever Ltd",       sector:"FMCG",           base:2341, color:"#FF9500", logo:"🧴",  exchange:"NSE", currency:"₹" },
  { symbol:"ICICIBANK", name:"ICICI Bank Ltd",               sector:"Banking",        base:1089, color:"#FF3B30", logo:"🏛️",  exchange:"NSE", currency:"₹" },
  { symbol:"SBIN",      name:"State Bank of India",          sector:"Banking",        base:812,  color:"#64D2FF", logo:"🏧",  exchange:"NSE", currency:"₹" },
  { symbol:"BHARTIARTL",name:"Bharti Airtel Ltd",            sector:"Telecom",        base:1287, color:"#FF2D55", logo:"📡",  exchange:"NSE", currency:"₹" },
  { symbol:"ITC",       name:"ITC Ltd",                      sector:"FMCG",           base:458,  color:"#BF5AF2", logo:"🚬",  exchange:"NSE", currency:"₹" },
  { symbol:"KOTAKBANK", name:"Kotak Mahindra Bank",          sector:"Banking",        base:1756, color:"#FF6B35", logo:"💳",  exchange:"NSE", currency:"₹" },
  { symbol:"LT",        name:"Larsen & Toubro Ltd",          sector:"Infrastructure", base:3412, color:"#30D158", logo:"🏗️",  exchange:"NSE", currency:"₹" },
  { symbol:"AXISBANK",  name:"Axis Bank Ltd",                sector:"Banking",        base:1123, color:"#007AFF", logo:"🔴",  exchange:"NSE", currency:"₹" },
  { symbol:"ASIANPAINT",name:"Asian Paints Ltd",             sector:"Consumer",       base:2876, color:"#FF9500", logo:"🎨",  exchange:"NSE", currency:"₹" },
  { symbol:"MARUTI",    name:"Maruti Suzuki India Ltd",      sector:"Auto",           base:11243,color:"#5856D6", logo:"🚗",  exchange:"NSE", currency:"₹" },
  { symbol:"BAJFINANCE",name:"Bajaj Finance Ltd",            sector:"Finance",        base:7234, color:"#FF3B30", logo:"💰",  exchange:"NSE", currency:"₹" },
  { symbol:"WIPRO",     name:"Wipro Ltd",                    sector:"IT",             base:478,  color:"#64D2FF", logo:"⚡",  exchange:"NSE", currency:"₹" },
  { symbol:"HCLTECH",   name:"HCL Technologies Ltd",         sector:"IT",             base:1389, color:"#30D158", logo:"🔷",  exchange:"NSE", currency:"₹" },
  { symbol:"SUNPHARMA", name:"Sun Pharmaceutical Ind.",      sector:"Pharma",         base:1642, color:"#FF9500", logo:"💊",  exchange:"NSE", currency:"₹" },
  { symbol:"TATAMOTORS",name:"Tata Motors Ltd",              sector:"Auto",           base:924,  color:"#FF6B35", logo:"🚙",  exchange:"NSE", currency:"₹" },
  { symbol:"ONGC",      name:"Oil & Natural Gas Corp",       sector:"Energy",         base:272,  color:"#BF5AF2", logo:"⛽",  exchange:"NSE", currency:"₹" },
  { symbol:"POWERGRID", name:"Power Grid Corp of India",     sector:"Utilities",      base:324,  color:"#FF2D55", logo:"🔌",  exchange:"NSE", currency:"₹" },
  { symbol:"NTPC",      name:"NTPC Ltd",                     sector:"Utilities",      base:368,  color:"#007AFF", logo:"⚡",  exchange:"NSE", currency:"₹" },
  { symbol:"JSWSTEEL",  name:"JSW Steel Ltd",                sector:"Metals",         base:876,  color:"#64D2FF", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"TATASTEEL", name:"Tata Steel Ltd",               sector:"Metals",         base:162,  color:"#FF3B30", logo:"🔩",  exchange:"NSE", currency:"₹" },
  { symbol:"M&M",       name:"Mahindra & Mahindra Ltd",      sector:"Auto",           base:2134, color:"#30D158", logo:"🚜",  exchange:"NSE", currency:"₹" },
  { symbol:"ULTRACEMCO",name:"UltraTech Cement Ltd",         sector:"Cement",         base:9876, color:"#FF9500", logo:"🏭",  exchange:"NSE", currency:"₹" },
  { symbol:"TITAN",     name:"Titan Company Ltd",            sector:"Consumer",       base:3312, color:"#5856D6", logo:"⌚",  exchange:"NSE", currency:"₹" },
  { symbol:"BAJAJFINSV",name:"Bajaj Finserv Ltd",            sector:"Finance",        base:1634, color:"#FF6B35", logo:"🏢",  exchange:"NSE", currency:"₹" },
  { symbol:"ADANIENT",  name:"Adani Enterprises Ltd",        sector:"Conglomerate",   base:2456, color:"#FF9500", logo:"🌐",  exchange:"NSE", currency:"₹" },
  { symbol:"ADANIPORTS",name:"Adani Ports & SEZ Ltd",        sector:"Logistics",      base:1287, color:"#007AFF", logo:"⚓",  exchange:"NSE", currency:"₹" },
  { symbol:"DIVISLAB",  name:"Divi's Laboratories Ltd",      sector:"Pharma",         base:4123, color:"#30D158", logo:"🧬",  exchange:"NSE", currency:"₹" },
  { symbol:"DRREDDY",   name:"Dr. Reddy's Laboratories",     sector:"Pharma",         base:6234, color:"#BF5AF2", logo:"💉",  exchange:"NSE", currency:"₹" },
  { symbol:"CIPLA",     name:"Cipla Ltd",                    sector:"Pharma",         base:1478, color:"#FF2D55", logo:"💊",  exchange:"NSE", currency:"₹" },
  { symbol:"GRASIM",    name:"Grasim Industries Ltd",        sector:"Cement",         base:2341, color:"#64D2FF", logo:"🏗️",  exchange:"NSE", currency:"₹" },
  { symbol:"HEROMOTOCO",name:"Hero MotoCorp Ltd",            sector:"Auto",           base:4512, color:"#FF3B30", logo:"🏍️",  exchange:"NSE", currency:"₹" },
  { symbol:"EICHERMOT", name:"Eicher Motors Ltd",            sector:"Auto",           base:4234, color:"#30D158", logo:"🛵",  exchange:"NSE", currency:"₹" },
  { symbol:"BPCL",      name:"Bharat Petroleum Corp",        sector:"Energy",         base:312,  color:"#FF9500", logo:"⛽",  exchange:"NSE", currency:"₹" },
  { symbol:"COALINDIA", name:"Coal India Ltd",               sector:"Energy",         base:478,  color:"#5856D6", logo:"⛏️",  exchange:"NSE", currency:"₹" },
  { symbol:"BRITANNIA", name:"Britannia Industries Ltd",     sector:"FMCG",           base:5234, color:"#FF6B35", logo:"🍪",  exchange:"NSE", currency:"₹" },
  { symbol:"NESTLEIND", name:"Nestle India Ltd",             sector:"FMCG",           base:2234, color:"#007AFF", logo:"☕",  exchange:"NSE", currency:"₹" },

  // ── INDIA: MIDCAP / SECTOR LEADERS ──────────────────────────
  { symbol:"ZOMATO",    name:"Zomato Ltd",                   sector:"Food Tech",      base:234,  color:"#FF3B30", logo:"🍕",  exchange:"NSE", currency:"₹" },
  { symbol:"NYKAA",     name:"FSN E-Commerce (Nykaa)",       sector:"E-Commerce",     base:178,  color:"#FF2D55", logo:"💄",  exchange:"NSE", currency:"₹" },
  { symbol:"PAYTM",     name:"One 97 Communications",        sector:"Fintech",        base:612,  color:"#007AFF", logo:"📱",  exchange:"NSE", currency:"₹" },
  { symbol:"POLICYBZR", name:"PB Fintech (PolicyBazaar)",    sector:"Insurtech",      base:1124, color:"#30D158", logo:"🛡️",  exchange:"NSE", currency:"₹" },
  { symbol:"DELHIVERY", name:"Delhivery Ltd",                sector:"Logistics",      base:387,  color:"#FF9500", logo:"📦",  exchange:"NSE", currency:"₹" },
  { symbol:"IRCTC",     name:"Indian Railway Catering Corp", sector:"Travel",         base:756,  color:"#BF5AF2", logo:"🚂",  exchange:"NSE", currency:"₹" },
  { symbol:"INDIGO",    name:"InterGlobe Aviation (IndiGo)", sector:"Aviation",       base:4123, color:"#5856D6", logo:"✈️",  exchange:"NSE", currency:"₹" },
  { symbol:"TATAPOWER", name:"Tata Power Company Ltd",       sector:"Utilities",      base:412,  color:"#FF6B35", logo:"🔆",  exchange:"NSE", currency:"₹" },
  { symbol:"HAVELLS",   name:"Havells India Ltd",            sector:"Consumer Elec",  base:1678, color:"#64D2FF", logo:"💡",  exchange:"NSE", currency:"₹" },
  { symbol:"PIDILITIND",name:"Pidilite Industries Ltd",      sector:"Chemicals",      base:2876, color:"#FF3B30", logo:"🔧",  exchange:"NSE", currency:"₹" },
  { symbol:"BERGEPAINT",name:"Berger Paints India Ltd",      sector:"Consumer",       base:534,  color:"#30D158", logo:"🖌️",  exchange:"NSE", currency:"₹" },
  { symbol:"MUTHOOTFIN",name:"Muthoot Finance Ltd",          sector:"Finance",        base:1876, color:"#FF9500", logo:"🥇",  exchange:"NSE", currency:"₹" },
  { symbol:"INDUSINDBK",name:"IndusInd Bank Ltd",            sector:"Banking",        base:1123, color:"#007AFF", logo:"💼",  exchange:"NSE", currency:"₹" },
  { symbol:"FEDERALBNK",name:"The Federal Bank Ltd",         sector:"Banking",        base:178,  color:"#5856D6", logo:"🏦",  exchange:"NSE", currency:"₹" },
  { symbol:"IDFCFIRSTB",name:"IDFC First Bank Ltd",          sector:"Banking",        base:82,   color:"#FF2D55", logo:"🏧",  exchange:"NSE", currency:"₹" },
  { symbol:"BANDHANBNK",name:"Bandhan Bank Ltd",             sector:"Banking",        base:212,  color:"#BF5AF2", logo:"🎯",  exchange:"NSE", currency:"₹" },
  { symbol:"TATACOMM",  name:"Tata Communications Ltd",      sector:"Telecom",        base:1823, color:"#FF6B35", logo:"📡",  exchange:"NSE", currency:"₹" },
  { symbol:"MPHASIS",   name:"Mphasis Ltd",                  sector:"IT",             base:2134, color:"#007AFF", logo:"💻",  exchange:"NSE", currency:"₹" },
  { symbol:"LTIMINDTREE",name:"LTIMindtree Ltd",             sector:"IT",             base:5234, color:"#30D158", logo:"🌿",  exchange:"NSE", currency:"₹" },
  { symbol:"PERSISTENT",name:"Persistent Systems Ltd",       sector:"IT",             base:4512, color:"#64D2FF", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"COFORGE",   name:"Coforge Ltd",                  sector:"IT",             base:6234, color:"#FF9500", logo:"🔷",  exchange:"NSE", currency:"₹" },
  { symbol:"ZYDUSLIFE", name:"Zydus Lifesciences Ltd",       sector:"Pharma",         base:956,  color:"#FF3B30", logo:"🧪",  exchange:"NSE", currency:"₹" },
  { symbol:"TORNTPHARM",name:"Torrent Pharmaceuticals",      sector:"Pharma",         base:2341, color:"#5856D6", logo:"💊",  exchange:"NSE", currency:"₹" },
  { symbol:"AUROPHARMA",name:"Aurobindo Pharma Ltd",         sector:"Pharma",         base:1098, color:"#BF5AF2", logo:"🏥",  exchange:"NSE", currency:"₹" },
  { symbol:"LUPIN",     name:"Lupin Ltd",                    sector:"Pharma",         base:1678, color:"#FF2D55", logo:"💉",  exchange:"NSE", currency:"₹" },
  { symbol:"ALKEM",     name:"Alkem Laboratories Ltd",       sector:"Pharma",         base:5678, color:"#007AFF", logo:"🧬",  exchange:"NSE", currency:"₹" },
  { symbol:"GLAND",     name:"Gland Pharma Ltd",             sector:"Pharma",         base:1789, color:"#30D158", logo:"⚗️",  exchange:"NSE", currency:"₹" },
  { symbol:"APOLLOHOSP",name:"Apollo Hospitals Enterprise",  sector:"Healthcare",     base:6789, color:"#FF6B35", logo:"🏥",  exchange:"NSE", currency:"₹" },
  { symbol:"FORTIS",    name:"Fortis Healthcare Ltd",        sector:"Healthcare",     base:456,  color:"#FF9500", logo:"⛑️",  exchange:"NSE", currency:"₹" },
  { symbol:"MAXHEALTH", name:"Max Healthcare Institute",     sector:"Healthcare",     base:812,  color:"#64D2FF", logo:"🩺",  exchange:"NSE", currency:"₹" },
  { symbol:"MOTHERSON", name:"Samvardhana Motherson Intl",   sector:"Auto Parts",     base:178,  color:"#FF3B30", logo:"🔧",  exchange:"NSE", currency:"₹" },
  { symbol:"BOSCHLTD",  name:"Bosch Ltd",                    sector:"Auto Parts",     base:34512,color:"#5856D6", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"BALKRISIND",name:"Balkrishna Industries Ltd",    sector:"Auto Parts",     base:2789, color:"#007AFF", logo:"🔵",  exchange:"NSE", currency:"₹" },
  { symbol:"APOLLOTYRE",name:"Apollo Tyres Ltd",             sector:"Auto Parts",     base:456,  color:"#FF2D55", logo:"🛞",  exchange:"NSE", currency:"₹" },
  { symbol:"GMRINFRA",  name:"GMR Airports Infrastructure",  sector:"Infrastructure", base:78,   color:"#30D158", logo:"✈️",  exchange:"NSE", currency:"₹" },
  { symbol:"PRESTIGE",  name:"Prestige Estates Projects",    sector:"Real Estate",    base:1678, color:"#BF5AF2", logo:"🏢",  exchange:"NSE", currency:"₹" },
  { symbol:"DLF",       name:"DLF Ltd",                      sector:"Real Estate",    base:812,  color:"#FF9500", logo:"🏗️",  exchange:"NSE", currency:"₹" },
  { symbol:"OBEROIRLTY",name:"Oberoi Realty Ltd",            sector:"Real Estate",    base:1789, color:"#FF6B35", logo:"🏨",  exchange:"NSE", currency:"₹" },
  { symbol:"TATAELXSI", name:"Tata Elxsi Ltd",               sector:"IT",             base:6789, color:"#007AFF", logo:"🎯",  exchange:"NSE", currency:"₹" },
  { symbol:"DIXON",     name:"Dixon Technologies (India)",   sector:"Electronics",    base:12345,color:"#64D2FF", logo:"📺",  exchange:"NSE", currency:"₹" },
  { symbol:"AMBER",     name:"Amber Enterprises India Ltd",  sector:"Electronics",    base:4512, color:"#FF3B30", logo:"❄️",  exchange:"NSE", currency:"₹" },
  { symbol:"KAYNES",    name:"Kaynes Technology India",      sector:"Electronics",    base:3456, color:"#30D158", logo:"🔌",  exchange:"NSE", currency:"₹" },
  { symbol:"CAMPUSACT", name:"Campus Activewear Ltd",        sector:"Consumer",       base:212,  color:"#FF9500", logo:"👟",  exchange:"NSE", currency:"₹" },
  { symbol:"VEDL",      name:"Vedanta Ltd",                  sector:"Metals",         base:312,  color:"#5856D6", logo:"⛏️",  exchange:"NSE", currency:"₹" },
  { symbol:"HINDALCO",  name:"Hindalco Industries Ltd",      sector:"Metals",         base:634,  color:"#BF5AF2", logo:"🔩",  exchange:"NSE", currency:"₹" },
  { symbol:"NMDC",      name:"NMDC Ltd",                     sector:"Metals",         base:234,  color:"#FF2D55", logo:"🪨",  exchange:"NSE", currency:"₹" },
  { symbol:"SAIL",      name:"Steel Authority of India",     sector:"Metals",         base:134,  color:"#007AFF", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"HDFCLIFE",  name:"HDFC Life Insurance Co",       sector:"Insurance",      base:634,  color:"#30D158", logo:"🛡️",  exchange:"NSE", currency:"₹" },
  { symbol:"SBILIFE",   name:"SBI Life Insurance Co",        sector:"Insurance",      base:1456, color:"#FF6B35", logo:"🔐",  exchange:"NSE", currency:"₹" },
  { symbol:"ICICIPRU",  name:"ICICI Prudential Life Ins",    sector:"Insurance",      base:678,  color:"#64D2FF", logo:"💎",  exchange:"NSE", currency:"₹" },
  { symbol:"NIACL",     name:"New India Assurance Co",       sector:"Insurance",      base:212,  color:"#FF3B30", logo:"🏛️",  exchange:"NSE", currency:"₹" },
  { symbol:"BAJAJHLDNG",name:"Bajaj Holdings & Inv Ltd",     sector:"Finance",        base:8912, color:"#FF9500", logo:"💼",  exchange:"NSE", currency:"₹" },
  { symbol:"CHOLAFIN",  name:"Cholamandalam Inv & Fin",      sector:"Finance",        base:1234, color:"#5856D6", logo:"💳",  exchange:"NSE", currency:"₹" },
  { symbol:"MANAPPURAM",name:"Manappuram Finance Ltd",       sector:"Finance",        base:212,  color:"#BF5AF2", logo:"🥇",  exchange:"NSE", currency:"₹" },
  { symbol:"PIIND",     name:"PI Industries Ltd",            sector:"Chemicals",      base:3456, color:"#007AFF", logo:"🌿",  exchange:"NSE", currency:"₹" },
  { symbol:"SRF",       name:"SRF Ltd",                      sector:"Chemicals",      base:2345, color:"#30D158", logo:"⚗️",  exchange:"NSE", currency:"₹" },
  { symbol:"AAVAS",     name:"Aavas Financiers Ltd",         sector:"Finance",        base:1789, color:"#FF2D55", logo:"🏠",  exchange:"NSE", currency:"₹" },
  { symbol:"CANFINHOME",name:"Can Fin Homes Ltd",            sector:"Finance",        base:867,  color:"#FF6B35", logo:"🏡",  exchange:"NSE", currency:"₹" },

  // ── INDIA: NIFTY 500 EXPANDED — PSU BANKS ──────────────────────
  { symbol:"PNB",       name:"Punjab National Bank",         sector:"Banking",        base:112,  color:"#FF6B35", logo:"🏦",  exchange:"NSE", currency:"₹" },
  { symbol:"BANKBARODA",name:"Bank of Baroda",               sector:"Banking",        base:248,  color:"#007AFF", logo:"🏛️",  exchange:"NSE", currency:"₹" },
  { symbol:"CANBK",     name:"Canara Bank",                  sector:"Banking",        base:112,  color:"#30D158", logo:"🏧",  exchange:"NSE", currency:"₹" },
  { symbol:"UNIONBANK", name:"Union Bank of India",          sector:"Banking",        base:134,  color:"#FF9500", logo:"🏦",  exchange:"NSE", currency:"₹" },
  { symbol:"IOB",       name:"Indian Overseas Bank",         sector:"Banking",        base:52,   color:"#5856D6", logo:"🏛️",  exchange:"NSE", currency:"₹" },
  { symbol:"INDIANB",   name:"Indian Bank",                  sector:"Banking",        base:534,  color:"#FF3B30", logo:"🏧",  exchange:"NSE", currency:"₹" },
  { symbol:"MAHABANK",  name:"Bank of Maharashtra",          sector:"Banking",        base:62,   color:"#BF5AF2", logo:"🏦",  exchange:"NSE", currency:"₹" },
  { symbol:"CENTRALBK", name:"Central Bank of India",        sector:"Banking",        base:56,   color:"#64D2FF", logo:"🏛️",  exchange:"NSE", currency:"₹" },
  { symbol:"UCOBANK",   name:"UCO Bank",                     sector:"Banking",        base:48,   color:"#FF2D55", logo:"🏧",  exchange:"NSE", currency:"₹" },
  { symbol:"BANKINDIA", name:"Bank of India",                sector:"Banking",        base:118,  color:"#FF6B35", logo:"🏦",  exchange:"NSE", currency:"₹" },
  { symbol:"PSB",       name:"Punjab & Sind Bank",           sector:"Banking",        base:58,   color:"#007AFF", logo:"🏛️",  exchange:"NSE", currency:"₹" },
  { symbol:"J&KBANK",   name:"J&K Bank Ltd",                 sector:"Banking",        base:118,  color:"#30D158", logo:"🏧",  exchange:"NSE", currency:"₹" },
  { symbol:"KTKBANK",   name:"Karnataka Bank Ltd",           sector:"Banking",        base:234,  color:"#FF9500", logo:"🏦",  exchange:"NSE", currency:"₹" },
  { symbol:"SOUTHBANK", name:"South Indian Bank Ltd",        sector:"Banking",        base:28,   color:"#5856D6", logo:"🏛️",  exchange:"NSE", currency:"₹" },
  { symbol:"CUB",       name:"City Union Bank Ltd",          sector:"Banking",        base:156,  color:"#FF3B30", logo:"🏧",  exchange:"NSE", currency:"₹" },
  { symbol:"KARURVYSYA",name:"Karur Vysya Bank Ltd",         sector:"Banking",        base:178,  color:"#BF5AF2", logo:"🏦",  exchange:"NSE", currency:"₹" },
  { symbol:"DCBBANK",   name:"DCB Bank Ltd",                 sector:"Banking",        base:112,  color:"#64D2FF", logo:"🏛️",  exchange:"NSE", currency:"₹" },
  { symbol:"RBLBANK",   name:"RBL Bank Ltd",                 sector:"Banking",        base:234,  color:"#FF2D55", logo:"🏧",  exchange:"NSE", currency:"₹" },
  { symbol:"YESBANK",   name:"Yes Bank Ltd",                 sector:"Banking",        base:22,   color:"#007AFF", logo:"🏦",  exchange:"NSE", currency:"₹" },
  { symbol:"AUBANK",    name:"AU Small Finance Bank",        sector:"Banking",        base:678,  color:"#30D158", logo:"🏛️",  exchange:"NSE", currency:"₹" },
  { symbol:"EQUITASBNK",name:"Equitas Small Fin Bank",       sector:"Banking",        base:92,   color:"#FF9500", logo:"🏧",  exchange:"NSE", currency:"₹" },
  { symbol:"UJJIVANSFB",name:"Ujjivan Small Fin Bank",       sector:"Banking",        base:42,   color:"#5856D6", logo:"🏦",  exchange:"NSE", currency:"₹" },

  // ── INDIA: DEFENCE & AEROSPACE ──────────────────────────────────
  { symbol:"HAL",       name:"Hindustan Aeronautics Ltd",    sector:"Defence",        base:4234, color:"#007AFF", logo:"✈️",  exchange:"NSE", currency:"₹" },
  { symbol:"BEL",       name:"Bharat Electronics Ltd",       sector:"Defence",        base:234,  color:"#30D158", logo:"📡",  exchange:"NSE", currency:"₹" },
  { symbol:"BDL",       name:"Bharat Dynamics Ltd",          sector:"Defence",        base:1234, color:"#FF6B35", logo:"🚀",  exchange:"NSE", currency:"₹" },
  { symbol:"COCHINSHIP",name:"Cochin Shipyard Ltd",          sector:"Defence",        base:1678, color:"#FF9500", logo:"🚢",  exchange:"NSE", currency:"₹" },
  { symbol:"GRSE",      name:"Garden Reach Shipbuilders",    sector:"Defence",        base:2123, color:"#5856D6", logo:"⚓",  exchange:"NSE", currency:"₹" },
  { symbol:"MAZAGON",   name:"Mazagon Dock Shipbuilders",    sector:"Defence",        base:3456, color:"#FF3B30", logo:"🛳️",  exchange:"NSE", currency:"₹" },
  { symbol:"PARAS",     name:"Paras Defence & Space Tech",   sector:"Defence",        base:1123, color:"#BF5AF2", logo:"🛰️",  exchange:"NSE", currency:"₹" },
  { symbol:"DATAPATTNS",name:"Data Patterns India Ltd",      sector:"Defence",        base:2345, color:"#64D2FF", logo:"📊",  exchange:"NSE", currency:"₹" },
  { symbol:"SOLARINDS", name:"Solar Industries India",       sector:"Defence",        base:8456, color:"#FF2D55", logo:"💥",  exchange:"NSE", currency:"₹" },
  { symbol:"BEML",      name:"BEML Ltd",                     sector:"Defence",        base:3234, color:"#007AFF", logo:"🔧",  exchange:"NSE", currency:"₹" },

  // ── INDIA: RENEWABLE ENERGY & POWER ─────────────────────────────
  { symbol:"ADANIGREEN",name:"Adani Green Energy Ltd",       sector:"Renewable Energy",base:1234, color:"#30D158", logo:"☀️",  exchange:"NSE", currency:"₹" },
  { symbol:"TATAPOWER", name:"Tata Power Company Ltd",       sector:"Utilities",      base:412,  color:"#FF6B35", logo:"🔆",  exchange:"NSE", currency:"₹" },
  { symbol:"NHPC",      name:"NHPC Ltd",                     sector:"Utilities",      base:82,   color:"#007AFF", logo:"💧",  exchange:"NSE", currency:"₹" },
  { symbol:"SJVN",      name:"SJVN Ltd",                     sector:"Utilities",      base:118,  color:"#FF9500", logo:"⚡",  exchange:"NSE", currency:"₹" },
  { symbol:"IREDA",     name:"Indian Renewable Energy Dev",  sector:"Renewable Energy",base:178,  color:"#30D158", logo:"🌱",  exchange:"NSE", currency:"₹" },
  { symbol:"RECLTD",    name:"REC Ltd",                      sector:"Utilities",      base:478,  color:"#5856D6", logo:"🔌",  exchange:"NSE", currency:"₹" },
  { symbol:"PFC",       name:"Power Finance Corporation",    sector:"Utilities",      base:412,  color:"#FF3B30", logo:"⚡",  exchange:"NSE", currency:"₹" },
  { symbol:"CESC",      name:"CESC Ltd",                     sector:"Utilities",      base:134,  color:"#BF5AF2", logo:"💡",  exchange:"NSE", currency:"₹" },
  { symbol:"TORNTPOWER",name:"Torrent Power Ltd",            sector:"Utilities",      base:1456, color:"#64D2FF", logo:"🔌",  exchange:"NSE", currency:"₹" },
  { symbol:"JSWINERGY", name:"JSW Energy Ltd",               sector:"Utilities",      base:456,  color:"#FF2D55", logo:"⚡",  exchange:"NSE", currency:"₹" },
  { symbol:"GREENPLY",  name:"Greenply Industries Ltd",      sector:"Building Material",base:234, color:"#30D158", logo:"🌲",  exchange:"NSE", currency:"₹" },
  { symbol:"SUZLON",    name:"Suzlon Energy Ltd",            sector:"Renewable Energy",base:42,   color:"#007AFF", logo:"🌬️",  exchange:"NSE", currency:"₹" },
  { symbol:"INOXWIND",  name:"Inox Wind Ltd",                sector:"Renewable Energy",base:178,  color:"#FF6B35", logo:"🌀",  exchange:"NSE", currency:"₹" },
  { symbol:"KPIGREENEG",name:"KPI Green Energy Ltd",         sector:"Renewable Energy",base:1234, color:"#30D158", logo:"☀️",  exchange:"NSE", currency:"₹" },
  { symbol:"WAAREENRGY",name:"Waaree Energies Ltd",          sector:"Renewable Energy",base:3456, color:"#FF9500", logo:"🔋",  exchange:"NSE", currency:"₹" },

  // ── INDIA: CEMENT & BUILDING MATERIALS ──────────────────────────
  { symbol:"SHREECEM",  name:"Shree Cement Ltd",             sector:"Cement",         base:26543,color:"#007AFF", logo:"🏗️",  exchange:"NSE", currency:"₹" },
  { symbol:"AMBUJACEM", name:"Ambuja Cements Ltd",           sector:"Cement",         base:612,  color:"#30D158", logo:"🏢",  exchange:"NSE", currency:"₹" },
  { symbol:"ACC",       name:"ACC Ltd",                      sector:"Cement",         base:2456, color:"#FF6B35", logo:"🏗️",  exchange:"NSE", currency:"₹" },
  { symbol:"RAMCOCEM",  name:"The Ramco Cements Ltd",        sector:"Cement",         base:912,  color:"#FF9500", logo:"🏭",  exchange:"NSE", currency:"₹" },
  { symbol:"JKCEMENT",  name:"JK Cement Ltd",                sector:"Cement",         base:3678, color:"#5856D6", logo:"🏗️",  exchange:"NSE", currency:"₹" },
  { symbol:"BIRLACORPN",name:"Birla Corporation Ltd",        sector:"Cement",         base:1234, color:"#FF3B30", logo:"🏭",  exchange:"NSE", currency:"₹" },
  { symbol:"DALMIACEM", name:"Dalmia Bharat Ltd",            sector:"Cement",         base:1789, color:"#BF5AF2", logo:"🏗️",  exchange:"NSE", currency:"₹" },
  { symbol:"INDIACEM",  name:"The India Cements Ltd",        sector:"Cement",         base:234,  color:"#64D2FF", logo:"🏭",  exchange:"NSE", currency:"₹" },
  { symbol:"PRISMJOHNS",name:"Prism Johnson Ltd",            sector:"Building Material",base:178, color:"#FF2D55", logo:"🧱",  exchange:"NSE", currency:"₹" },
  { symbol:"JKLAKSHMI", name:"JK Lakshmi Cement Ltd",        sector:"Cement",         base:812,  color:"#007AFF", logo:"🏗️",  exchange:"NSE", currency:"₹" },
  { symbol:"HEIDELBERG",name:"Heidelberg Cement India",       sector:"Cement",         base:212,  color:"#30D158", logo:"🏭",  exchange:"NSE", currency:"₹" },

  // ── INDIA: CHEMICALS & FERTILIZERS ──────────────────────────────
  { symbol:"NAVINFLUOR",name:"Navin Fluorine Intl Ltd",      sector:"Chemicals",      base:3456, color:"#007AFF", logo:"⚗️",  exchange:"NSE", currency:"₹" },
  { symbol:"ATULLTD",   name:"Atul Ltd",                     sector:"Chemicals",      base:6789, color:"#30D158", logo:"🧪",  exchange:"NSE", currency:"₹" },
  { symbol:"DEEPAKNTR", name:"Deepak Nitrite Ltd",           sector:"Chemicals",      base:2123, color:"#FF6B35", logo:"⚗️",  exchange:"NSE", currency:"₹" },
  { symbol:"CLEAN",     name:"Clean Science & Technology",   sector:"Chemicals",      base:1456, color:"#FF9500", logo:"🧬",  exchange:"NSE", currency:"₹" },
  { symbol:"FINEORG",   name:"Fine Organic Industries",      sector:"Chemicals",      base:4567, color:"#5856D6", logo:"⚗️",  exchange:"NSE", currency:"₹" },
  { symbol:"AARTIIND",  name:"Aarti Industries Ltd",         sector:"Chemicals",      base:567,  color:"#FF3B30", logo:"🧪",  exchange:"NSE", currency:"₹" },
  { symbol:"FLUOROCHEM",name:"Gujarat Fluorochemicals",      sector:"Chemicals",      base:3234, color:"#BF5AF2", logo:"⚗️",  exchange:"NSE", currency:"₹" },
  { symbol:"TATACHEM",  name:"Tata Chemicals Ltd",           sector:"Chemicals",      base:1089, color:"#64D2FF", logo:"🧬",  exchange:"NSE", currency:"₹" },
  { symbol:"COROMANDEL",name:"Coromandel International",     sector:"Fertilizers",    base:1234, color:"#30D158", logo:"🌾",  exchange:"NSE", currency:"₹" },
  { symbol:"UPL",       name:"UPL Ltd",                      sector:"Agrochemicals",  base:512,  color:"#FF2D55", logo:"🌱",  exchange:"NSE", currency:"₹" },
  { symbol:"CHAMBLFERT",name:"Chambal Fertilisers",          sector:"Fertilizers",    base:334,  color:"#007AFF", logo:"🌿",  exchange:"NSE", currency:"₹" },
  { symbol:"GNFC",      name:"Gujarat Narmada Valley Fert",  sector:"Fertilizers",    base:612,  color:"#FF6B35", logo:"🌾",  exchange:"NSE", currency:"₹" },
  { symbol:"DEEPAKFERT",name:"Deepak Fertilisers",           sector:"Fertilizers",    base:534,  color:"#FF9500", logo:"🌱",  exchange:"NSE", currency:"₹" },
  { symbol:"RALLIS",    name:"Rallis India Ltd",             sector:"Agrochemicals",  base:278,  color:"#5856D6", logo:"🌿",  exchange:"NSE", currency:"₹" },

  // ── INDIA: TEXTILES & FASHION ───────────────────────────────────
  { symbol:"PAGEIND",   name:"Page Industries Ltd",          sector:"Textiles",       base:38456,color:"#007AFF", logo:"👕",  exchange:"NSE", currency:"₹" },
  { symbol:"TRENT",     name:"Trent Ltd (Westside/Zudio)",   sector:"Retail",         base:4567, color:"#30D158", logo:"🛍️",  exchange:"NSE", currency:"₹" },
  { symbol:"ABFRL",     name:"Aditya Birla Fashion Retail",  sector:"Retail",         base:234,  color:"#FF6B35", logo:"👔",  exchange:"NSE", currency:"₹" },
  { symbol:"RAYMOND",   name:"Raymond Ltd",                  sector:"Textiles",       base:1678, color:"#FF9500", logo:"🎩",  exchange:"NSE", currency:"₹" },
  { symbol:"ARVIND",    name:"Arvind Ltd",                   sector:"Textiles",       base:312,  color:"#5856D6", logo:"👖",  exchange:"NSE", currency:"₹" },
  { symbol:"KPRMILL",   name:"KPR Mill Ltd",                 sector:"Textiles",       base:678,  color:"#FF3B30", logo:"🧵",  exchange:"NSE", currency:"₹" },
  { symbol:"VEDANTFASH",name:"Vedant Fashions Ltd (Manyavar)",sector:"Retail",        base:1123, color:"#BF5AF2", logo:"👘",  exchange:"NSE", currency:"₹" },
  { symbol:"SHOPERSTOP",name:"Shoppers Stop Ltd",            sector:"Retail",         base:712,  color:"#64D2FF", logo:"🏬",  exchange:"NSE", currency:"₹" },
  { symbol:"VMART",     name:"V-Mart Retail Ltd",            sector:"Retail",         base:1789, color:"#FF2D55", logo:"🛒",  exchange:"NSE", currency:"₹" },
  { symbol:"TATACONSUM",name:"Tata Consumer Products Ltd",   sector:"FMCG",           base:912,  color:"#007AFF", logo:"☕",  exchange:"NSE", currency:"₹" },
  { symbol:"METROBRAND",name:"Metro Brands Ltd",             sector:"Retail",         base:1234, color:"#FF6B35", logo:"👞",  exchange:"NSE", currency:"₹" },

  // ── INDIA: MEDIA & ENTERTAINMENT ────────────────────────────────
  { symbol:"ZEEL",      name:"Zee Entertainment Ltd",        sector:"Media",          base:234,  color:"#007AFF", logo:"📺",  exchange:"NSE", currency:"₹" },
  { symbol:"PVRINOX",   name:"PVR INOX Ltd",                 sector:"Media",          base:1456, color:"#30D158", logo:"🎬",  exchange:"NSE", currency:"₹" },
  { symbol:"SUNTV",     name:"Sun TV Network Ltd",           sector:"Media",          base:612,  color:"#FF6B35", logo:"📡",  exchange:"NSE", currency:"₹" },
  { symbol:"SAREGAMA",  name:"Saregama India Ltd",           sector:"Media",          base:456,  color:"#FF9500", logo:"🎵",  exchange:"NSE", currency:"₹" },
  { symbol:"NAZARA",    name:"Nazara Technologies Ltd",      sector:"Gaming",         base:789,  color:"#5856D6", logo:"🎮",  exchange:"NSE", currency:"₹" },
  { symbol:"NETWORK18", name:"Network18 Media & Inv",        sector:"Media",          base:78,   color:"#FF3B30", logo:"📰",  exchange:"NSE", currency:"₹" },
  { symbol:"TV18BRDCST",name:"TV18 Broadcast Ltd",           sector:"Media",          base:45,   color:"#BF5AF2", logo:"📡",  exchange:"NSE", currency:"₹" },

  // ── INDIA: HOSPITALITY & TOURISM ────────────────────────────────
  { symbol:"INDHOTEL",  name:"Indian Hotels Co Ltd (Taj)",   sector:"Hospitality",    base:534,  color:"#007AFF", logo:"🏨",  exchange:"NSE", currency:"₹" },
  { symbol:"LEMONTRE",  name:"Lemon Tree Hotels Ltd",        sector:"Hospitality",    base:112,  color:"#30D158", logo:"🌴",  exchange:"NSE", currency:"₹" },
  { symbol:"EIHOTEL",   name:"EIH Ltd (Oberoi Hotels)",     sector:"Hospitality",    base:278,  color:"#FF6B35", logo:"🏰",  exchange:"NSE", currency:"₹" },
  { symbol:"CHALET",    name:"Chalet Hotels Ltd",            sector:"Hospitality",    base:678,  color:"#FF9500", logo:"🏡",  exchange:"NSE", currency:"₹" },
  { symbol:"THOMASCOOK",name:"Thomas Cook India Ltd",        sector:"Travel",         base:178,  color:"#5856D6", logo:"✈️",  exchange:"NSE", currency:"₹" },
  { symbol:"MAHINDHOIL",name:"Mahindra Holidays & Resorts",  sector:"Hospitality",    base:334,  color:"#FF3B30", logo:"🌊",  exchange:"NSE", currency:"₹" },
  { symbol:"EASEHOTL",  name:"Easy Trip Planners Ltd",       sector:"Travel",         base:42,   color:"#BF5AF2", logo:"🧳",  exchange:"NSE", currency:"₹" },
  { symbol:"YATRA",     name:"Yatra Online Ltd",             sector:"Travel",         base:156,  color:"#64D2FF", logo:"🌍",  exchange:"NSE", currency:"₹" },

  // ── INDIA: SUGAR, ETHANOL & AGRI ────────────────────────────────
  { symbol:"BALRAMCHIN",name:"Balrampur Chini Mills",        sector:"Sugar",          base:412,  color:"#007AFF", logo:"🍬",  exchange:"NSE", currency:"₹" },
  { symbol:"DHAMPUR",   name:"Dhampur Sugar Mills",          sector:"Sugar",          base:178,  color:"#30D158", logo:"🌾",  exchange:"NSE", currency:"₹" },
  { symbol:"RENUKA",    name:"Shree Renuka Sugars Ltd",      sector:"Sugar",          base:52,   color:"#FF6B35", logo:"🍬",  exchange:"NSE", currency:"₹" },
  { symbol:"TRIVENI",   name:"Triveni Engineering",          sector:"Sugar",          base:356,  color:"#FF9500", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"DWARIKESH", name:"Dwarikesh Sugar Industries",   sector:"Sugar",          base:78,   color:"#5856D6", logo:"🌾",  exchange:"NSE", currency:"₹" },
  { symbol:"GODREJAGRO",name:"Godrej Agrovet Ltd",           sector:"Agriculture",    base:534,  color:"#30D158", logo:"🐄",  exchange:"NSE", currency:"₹" },
  { symbol:"AVANTIFEED",name:"Avanti Feeds Ltd",             sector:"Agriculture",    base:456,  color:"#FF3B30", logo:"🦐",  exchange:"NSE", currency:"₹" },

  // ── INDIA: OIL, GAS & ENERGY ────────────────────────────────────
  { symbol:"IOC",       name:"Indian Oil Corporation",       sector:"Energy",         base:134,  color:"#FF6B35", logo:"⛽",  exchange:"NSE", currency:"₹" },
  { symbol:"HINDPETRO", name:"Hindustan Petroleum Corp",     sector:"Energy",         base:278,  color:"#007AFF", logo:"🛢️",  exchange:"NSE", currency:"₹" },
  { symbol:"GAIL",      name:"GAIL India Ltd",               sector:"Energy",         base:178,  color:"#30D158", logo:"🔥",  exchange:"NSE", currency:"₹" },
  { symbol:"PETRONET",  name:"Petronet LNG Ltd",             sector:"Energy",         base:234,  color:"#FF9500", logo:"⛽",  exchange:"NSE", currency:"₹" },
  { symbol:"MGL",       name:"Mahanagar Gas Ltd",            sector:"Energy",         base:1234, color:"#5856D6", logo:"🔥",  exchange:"NSE", currency:"₹" },
  { symbol:"IGL",       name:"Indraprastha Gas Ltd",         sector:"Energy",         base:456,  color:"#FF3B30", logo:"💨",  exchange:"NSE", currency:"₹" },
  { symbol:"GUJGASLTD", name:"Gujarat Gas Ltd",              sector:"Energy",         base:512,  color:"#BF5AF2", logo:"🔥",  exchange:"NSE", currency:"₹" },
  { symbol:"OIL",       name:"Oil India Ltd",                sector:"Energy",         base:312,  color:"#64D2FF", logo:"🛢️",  exchange:"NSE", currency:"₹" },
  { symbol:"MRPL",      name:"MRPL (Mangalore Refinery)",    sector:"Energy",         base:178,  color:"#FF2D55", logo:"⛽",  exchange:"NSE", currency:"₹" },
  { symbol:"CHENNPETRO",name:"Chennai Petroleum Corp",       sector:"Energy",         base:634,  color:"#007AFF", logo:"🛢️",  exchange:"NSE", currency:"₹" },

  // ── INDIA: PSU & GOVT ENTERPRISES ───────────────────────────────
  { symbol:"LIC",       name:"Life Insurance Corp of India", sector:"Insurance",      base:912,  color:"#007AFF", logo:"🏛️",  exchange:"NSE", currency:"₹" },
  { symbol:"IRFC",      name:"Indian Railway Finance Corp",  sector:"Finance",        base:134,  color:"#30D158", logo:"🚂",  exchange:"NSE", currency:"₹" },
  { symbol:"CONCOR",    name:"Container Corp of India",      sector:"Logistics",      base:756,  color:"#FF6B35", logo:"📦",  exchange:"NSE", currency:"₹" },
  { symbol:"BHEL",      name:"Bharat Heavy Electricals",     sector:"Capital Goods",  base:234,  color:"#FF9500", logo:"⚡",  exchange:"NSE", currency:"₹" },
  { symbol:"ENGINERSIN",name:"Engineers India Ltd",          sector:"Capital Goods",  base:178,  color:"#5856D6", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"NBCC",      name:"NBCC India Ltd",               sector:"Infrastructure", base:78,   color:"#FF3B30", logo:"🏗️",  exchange:"NSE", currency:"₹" },
  { symbol:"RVNL",      name:"Rail Vikas Nigam Ltd",         sector:"Infrastructure", base:212,  color:"#BF5AF2", logo:"🛤️",  exchange:"NSE", currency:"₹" },
  { symbol:"NLC",       name:"NLC India Ltd",                sector:"Utilities",      base:234,  color:"#64D2FF", logo:"⚡",  exchange:"NSE", currency:"₹" },
  { symbol:"HUDCO",     name:"Housing & Urban Dev Corp",     sector:"Finance",        base:178,  color:"#FF2D55", logo:"🏘️",  exchange:"NSE", currency:"₹" },
  { symbol:"RITES",     name:"RITES Ltd",                    sector:"Infrastructure", base:534,  color:"#007AFF", logo:"🚧",  exchange:"NSE", currency:"₹" },
  { symbol:"IRCON",     name:"IRCON International Ltd",      sector:"Infrastructure", base:178,  color:"#30D158", logo:"🏗️",  exchange:"NSE", currency:"₹" },
  { symbol:"NATIONALUM",name:"National Aluminium Co Ltd",    sector:"Metals",         base:112,  color:"#FF6B35", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"MOIL",      name:"MOIL Ltd",                     sector:"Metals",         base:312,  color:"#FF9500", logo:"⛏️",  exchange:"NSE", currency:"₹" },
  { symbol:"HFCL",      name:"HFCL Ltd",                     sector:"Telecom",        base:98,   color:"#5856D6", logo:"📡",  exchange:"NSE", currency:"₹" },
  { symbol:"RAILTEL",   name:"RailTel Corporation",          sector:"IT",             base:312,  color:"#FF3B30", logo:"📡",  exchange:"NSE", currency:"₹" },

  // ── INDIA: CONSUMER & FMCG ──────────────────────────────────────
  { symbol:"MARICO",    name:"Marico Ltd",                   sector:"FMCG",           base:567,  color:"#30D158", logo:"🧴",  exchange:"NSE", currency:"₹" },
  { symbol:"DABUR",     name:"Dabur India Ltd",              sector:"FMCG",           base:534,  color:"#007AFF", logo:"🌿",  exchange:"NSE", currency:"₹" },
  { symbol:"GODREJCP",  name:"Godrej Consumer Products",     sector:"FMCG",           base:1234, color:"#FF6B35", logo:"🧼",  exchange:"NSE", currency:"₹" },
  { symbol:"COLPAL",    name:"Colgate-Palmolive India",      sector:"FMCG",           base:2567, color:"#FF9500", logo:"🪥",  exchange:"NSE", currency:"₹" },
  { symbol:"EMAMILTD",  name:"Emami Ltd",                    sector:"FMCG",           base:512,  color:"#5856D6", logo:"🧴",  exchange:"NSE", currency:"₹" },
  { symbol:"BATAINDIA", name:"Bata India Ltd",               sector:"Consumer",       base:1456, color:"#FF3B30", logo:"👟",  exchange:"NSE", currency:"₹" },
  { symbol:"RELAXO",    name:"Relaxo Footwears Ltd",         sector:"Consumer",       base:789,  color:"#BF5AF2", logo:"🩴",  exchange:"NSE", currency:"₹" },
  { symbol:"JUBLFOOD",  name:"Jubilant FoodWorks Ltd",       sector:"Food & Beverage",base:512,  color:"#64D2FF", logo:"🍕",  exchange:"NSE", currency:"₹" },
  { symbol:"DEVYANI",   name:"Devyani International (KFC/PH)",sector:"Food & Beverage",base:178, color:"#FF2D55", logo:"🍗",  exchange:"NSE", currency:"₹" },
  { symbol:"WESTLIFE",  name:"Westlife Foodworld Ltd (McD)", sector:"Food & Beverage",base:789,  color:"#FFD60A", logo:"🍔",  exchange:"NSE", currency:"₹" },
  { symbol:"SAPRESTRANT",name:"Sapphire Foods India",        sector:"Food & Beverage",base:1234, color:"#007AFF", logo:"🍕",  exchange:"NSE", currency:"₹" },
  { symbol:"VBLINDS",   name:"V.I.P Industries Ltd",         sector:"Consumer",       base:534,  color:"#30D158", logo:"🧳",  exchange:"NSE", currency:"₹" },
  { symbol:"JYOTHYLABS",name:"Jyothy Labs Ltd",              sector:"FMCG",           base:312,  color:"#FF6B35", logo:"🧹",  exchange:"NSE", currency:"₹" },
  { symbol:"TATAPAWR",  name:"Tata Coffee (Tata Consumer)",  sector:"FMCG",           base:234,  color:"#FF9500", logo:"☕",  exchange:"NSE", currency:"₹" },
  { symbol:"MCDOWELL",  name:"United Spirits Ltd (Diageo)",  sector:"Beverages",      base:1234, color:"#5856D6", logo:"🥃",  exchange:"NSE", currency:"₹" },
  { symbol:"UBL",       name:"United Breweries Ltd",         sector:"Beverages",      base:1567, color:"#FF3B30", logo:"🍺",  exchange:"NSE", currency:"₹" },
  { symbol:"RADICO",    name:"Radico Khaitan Ltd",           sector:"Beverages",      base:1234, color:"#BF5AF2", logo:"🥂",  exchange:"NSE", currency:"₹" },

  // ── INDIA: IT & TECH (ADDITIONAL) ───────────────────────────────
  { symbol:"TECHM",     name:"Tech Mahindra Ltd",            sector:"IT",             base:1234, color:"#007AFF", logo:"💻",  exchange:"NSE", currency:"₹" },
  { symbol:"INFOEDGE",  name:"Info Edge India (Naukri)",     sector:"IT",             base:4567, color:"#30D158", logo:"💼",  exchange:"NSE", currency:"₹" },
  { symbol:"ROUTE",     name:"Route Mobile Ltd",             sector:"IT",             base:1678, color:"#FF6B35", logo:"📱",  exchange:"NSE", currency:"₹" },
  { symbol:"HAPPSTMNDS",name:"Happiest Minds Technologies",  sector:"IT",             base:789,  color:"#FF9500", logo:"😊",  exchange:"NSE", currency:"₹" },
  { symbol:"CYIENT",    name:"Cyient Ltd",                   sector:"IT",             base:1789, color:"#5856D6", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"ZENSAR",    name:"Zensar Technologies Ltd",      sector:"IT",             base:478,  color:"#FF3B30", logo:"💻",  exchange:"NSE", currency:"₹" },
  { symbol:"BIRLASOFT", name:"Birlasoft Ltd",                sector:"IT",             base:534,  color:"#BF5AF2", logo:"🔷",  exchange:"NSE", currency:"₹" },
  { symbol:"SONATA",    name:"Sonata Software Ltd",          sector:"IT",             base:612,  color:"#64D2FF", logo:"🎵",  exchange:"NSE", currency:"₹" },
  { symbol:"MASTEK",    name:"Mastek Ltd",                   sector:"IT",             base:2345, color:"#FF2D55", logo:"💻",  exchange:"NSE", currency:"₹" },
  { symbol:"LATENTVIEW", name:"Latent View Analytics Ltd",   sector:"IT",             base:378,  color:"#007AFF", logo:"📊",  exchange:"NSE", currency:"₹" },
  { symbol:"NEWGEN",    name:"Newgen Software Tech Ltd",     sector:"IT",             base:912,  color:"#30D158", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"INTELLECT", name:"Intellect Design Arena Ltd",   sector:"IT",             base:734,  color:"#FF6B35", logo:"🧠",  exchange:"NSE", currency:"₹" },
  { symbol:"TANLA",     name:"Tanla Platforms Ltd",          sector:"IT",             base:912,  color:"#FF9500", logo:"📡",  exchange:"NSE", currency:"₹" },
  { symbol:"QUESS",     name:"Quess Corp Ltd",               sector:"IT",             base:534,  color:"#5856D6", logo:"💼",  exchange:"NSE", currency:"₹" },
  { symbol:"FIRSTSOURC",name:"Firstsource Solutions Ltd",    sector:"IT",             base:178,  color:"#FF3B30", logo:"📞",  exchange:"NSE", currency:"₹" },

  // ── INDIA: PHARMA & HEALTHCARE (ADDITIONAL) ────────────────────
  { symbol:"BIOCON",    name:"Biocon Ltd",                   sector:"Pharma",         base:278,  color:"#30D158", logo:"🧬",  exchange:"NSE", currency:"₹" },
  { symbol:"LALPATHLAB",name:"Dr Lal PathLabs Ltd",          sector:"Healthcare",     base:2345, color:"#007AFF", logo:"🔬",  exchange:"NSE", currency:"₹" },
  { symbol:"METROPOLIS",name:"Metropolis Healthcare Ltd",    sector:"Healthcare",     base:1567, color:"#FF6B35", logo:"🏥",  exchange:"NSE", currency:"₹" },
  { symbol:"SYNGENE",   name:"Syngene International Ltd",    sector:"Pharma",         base:789,  color:"#FF9500", logo:"🧪",  exchange:"NSE", currency:"₹" },
  { symbol:"NATCOPHAR", name:"Natco Pharma Ltd",             sector:"Pharma",         base:756,  color:"#5856D6", logo:"💊",  exchange:"NSE", currency:"₹" },
  { symbol:"IPCALAB",   name:"IPCA Laboratories Ltd",        sector:"Pharma",         base:1089, color:"#FF3B30", logo:"💊",  exchange:"NSE", currency:"₹" },
  { symbol:"AJANTPHARM",name:"Ajanta Pharma Ltd",            sector:"Pharma",         base:2234, color:"#BF5AF2", logo:"💉",  exchange:"NSE", currency:"₹" },
  { symbol:"ABBOTINDIA",name:"Abbott India Ltd",             sector:"Pharma",         base:24567,color:"#64D2FF", logo:"💊",  exchange:"NSE", currency:"₹" },
  { symbol:"GLAXO",     name:"GlaxoSmithKline Pharma India", sector:"Pharma",         base:1789, color:"#FF2D55", logo:"💊",  exchange:"NSE", currency:"₹" },
  { symbol:"PFIZER",    name:"Pfizer Ltd (India)",           sector:"Pharma",         base:4567, color:"#007AFF", logo:"💉",  exchange:"NSE", currency:"₹" },
  { symbol:"MANKIND",   name:"Mankind Pharma Ltd",           sector:"Pharma",         base:2123, color:"#30D158", logo:"💊",  exchange:"NSE", currency:"₹" },
  { symbol:"MEDPLUS",   name:"MedPlus Health Services",      sector:"Healthcare",     base:678,  color:"#FF6B35", logo:"🏪",  exchange:"NSE", currency:"₹" },

  // ── INDIA: AUTO & AUTO PARTS (ADDITIONAL) ───────────────────────
  { symbol:"BAJAJ-AUTO",name:"Bajaj Auto Ltd",               sector:"Auto",           base:7234, color:"#007AFF", logo:"🏍️",  exchange:"NSE", currency:"₹" },
  { symbol:"TVSMOTOR",  name:"TVS Motor Company Ltd",        sector:"Auto",           base:1789, color:"#30D158", logo:"🛵",  exchange:"NSE", currency:"₹" },
  { symbol:"ASHOKLEY",  name:"Ashok Leyland Ltd",            sector:"Auto",           base:178,  color:"#FF6B35", logo:"🚛",  exchange:"NSE", currency:"₹" },
  { symbol:"ESCORTS",   name:"Escorts Kubota Ltd",           sector:"Auto",           base:3456, color:"#FF9500", logo:"🚜",  exchange:"NSE", currency:"₹" },
  { symbol:"FORCEMOT",  name:"Force Motors Ltd",             sector:"Auto",           base:6789, color:"#5856D6", logo:"🚙",  exchange:"NSE", currency:"₹" },
  { symbol:"TATAMTRDVR",name:"Tata Motors DVR",              sector:"Auto",           base:567,  color:"#FF3B30", logo:"🚗",  exchange:"NSE", currency:"₹" },
  { symbol:"OLAELEC",   name:"Ola Electric Mobility Ltd",    sector:"EV/Auto",        base:134,  color:"#30D158", logo:"🛵",  exchange:"NSE", currency:"₹" },
  { symbol:"ABOROENT",  name:"Ather Energy Ltd",             sector:"EV/Auto",        base:312,  color:"#BF5AF2", logo:"⚡",  exchange:"NSE", currency:"₹" },
  { symbol:"ENDURANCE", name:"Endurance Technologies",       sector:"Auto Parts",     base:1789, color:"#64D2FF", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"SUNDRMFAST",name:"Sundram Fasteners Ltd",        sector:"Auto Parts",     base:1089, color:"#FF2D55", logo:"🔩",  exchange:"NSE", currency:"₹" },
  { symbol:"EXIDEIND",  name:"Exide Industries Ltd",         sector:"Auto Parts",     base:289,  color:"#007AFF", logo:"🔋",  exchange:"NSE", currency:"₹" },
  { symbol:"AMARARAJA", name:"Amara Raja Energy Ltd",        sector:"Auto Parts",     base:712,  color:"#30D158", logo:"🔋",  exchange:"NSE", currency:"₹" },
  { symbol:"CEATLTD",   name:"CEAT Ltd",                     sector:"Auto Parts",     base:2456, color:"#FF6B35", logo:"🛞",  exchange:"NSE", currency:"₹" },
  { symbol:"MINDA",     name:"Uno Minda Ltd",                sector:"Auto Parts",     base:789,  color:"#FF9500", logo:"💡",  exchange:"NSE", currency:"₹" },
  { symbol:"SCHAEFFLER",name:"Schaeffler India Ltd",         sector:"Auto Parts",     base:3456, color:"#5856D6", logo:"⚙️",  exchange:"NSE", currency:"₹" },

  // ── INDIA: LOGISTICS & SUPPLY CHAIN ─────────────────────────────
  { symbol:"BLUEDART",  name:"Blue Dart Express Ltd",        sector:"Logistics",      base:7234, color:"#007AFF", logo:"✈️",  exchange:"NSE", currency:"₹" },
  { symbol:"TCI",       name:"Transport Corp of India Ltd",  sector:"Logistics",      base:856,  color:"#30D158", logo:"🚛",  exchange:"NSE", currency:"₹" },
  { symbol:"ALLCARGO",  name:"Allcargo Logistics Ltd",       sector:"Logistics",      base:378,  color:"#FF6B35", logo:"📦",  exchange:"NSE", currency:"₹" },
  { symbol:"MAHSEAMLES",name:"Maharashtra Seamless Ltd",     sector:"Metals",         base:612,  color:"#FF9500", logo:"🔩",  exchange:"NSE", currency:"₹" },
  { symbol:"GESHIP",    name:"Great Eastern Shipping Co",    sector:"Logistics",      base:912,  color:"#5856D6", logo:"🚢",  exchange:"NSE", currency:"₹" },
  { symbol:"SHIPPINGCR",name:"Shipping Corp of India",       sector:"Logistics",      base:212,  color:"#FF3B30", logo:"🚢",  exchange:"NSE", currency:"₹" },

  // ── INDIA: REAL ESTATE (ADDITIONAL) ─────────────────────────────
  { symbol:"GODREJPROP",name:"Godrej Properties Ltd",        sector:"Real Estate",    base:2567, color:"#007AFF", logo:"🏢",  exchange:"NSE", currency:"₹" },
  { symbol:"PHOENIXLTD",name:"Phoenix Mills Ltd",            sector:"Real Estate",    base:1789, color:"#30D158", logo:"🏬",  exchange:"NSE", currency:"₹" },
  { symbol:"BRIGADE",   name:"Brigade Enterprises Ltd",      sector:"Real Estate",    base:912,  color:"#FF6B35", logo:"🏗️",  exchange:"NSE", currency:"₹" },
  { symbol:"SOBHA",     name:"Sobha Ltd",                    sector:"Real Estate",    base:912,  color:"#FF9500", logo:"🏠",  exchange:"NSE", currency:"₹" },
  { symbol:"SUNTECK",   name:"Sunteck Realty Ltd",           sector:"Real Estate",    base:456,  color:"#5856D6", logo:"🏙️",  exchange:"NSE", currency:"₹" },
  { symbol:"MACROTECH", name:"Macrotech Developers (Lodha)", sector:"Real Estate",    base:1234, color:"#FF3B30", logo:"🏢",  exchange:"NSE", currency:"₹" },
  { symbol:"RAYMOND",   name:"Raymond Realty",               sector:"Real Estate",    base:456,  color:"#BF5AF2", logo:"🏗️",  exchange:"NSE", currency:"₹" },

  // ── INDIA: CAPITAL GOODS & ENGINEERING ──────────────────────────
  { symbol:"SIEMENS",   name:"Siemens Ltd",                  sector:"Capital Goods",  base:5678, color:"#007AFF", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"ABB",       name:"ABB India Ltd",                sector:"Capital Goods",  base:5234, color:"#30D158", logo:"🔌",  exchange:"NSE", currency:"₹" },
  { symbol:"HONAUT",    name:"Honeywell Automation India",   sector:"Capital Goods",  base:42567,color:"#FF6B35", logo:"🏭",  exchange:"NSE", currency:"₹" },
  { symbol:"CUMMINSIND",name:"Cummins India Ltd",            sector:"Capital Goods",  base:2345, color:"#FF9500", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"THERMAX",   name:"Thermax Ltd",                  sector:"Capital Goods",  base:3456, color:"#5856D6", logo:"🔥",  exchange:"NSE", currency:"₹" },
  { symbol:"CROMPTON",  name:"Crompton Greaves Consumer",    sector:"Consumer Elec",  base:312,  color:"#FF3B30", logo:"💡",  exchange:"NSE", currency:"₹" },
  { symbol:"VOLTAS",    name:"Voltas Ltd",                   sector:"Consumer Elec",  base:1123, color:"#BF5AF2", logo:"❄️",  exchange:"NSE", currency:"₹" },
  { symbol:"BLUESTAR",  name:"Blue Star Ltd",                sector:"Consumer Elec",  base:1234, color:"#64D2FF", logo:"❄️",  exchange:"NSE", currency:"₹" },
  { symbol:"KEIIND",    name:"KEI Industries Ltd",           sector:"Capital Goods",  base:3456, color:"#FF2D55", logo:"🔌",  exchange:"NSE", currency:"₹" },
  { symbol:"POLYCAB",   name:"Polycab India Ltd",            sector:"Capital Goods",  base:5678, color:"#007AFF", logo:"🔌",  exchange:"NSE", currency:"₹" },
  { symbol:"APLAPOLLO", name:"APL Apollo Tubes Ltd",         sector:"Capital Goods",  base:1567, color:"#30D158", logo:"🔩",  exchange:"NSE", currency:"₹" },
  { symbol:"GRINDWELL", name:"Grindwell Norton Ltd",         sector:"Capital Goods",  base:2123, color:"#FF6B35", logo:"⚙️",  exchange:"NSE", currency:"₹" },
  { symbol:"ELGIEQUIP", name:"Elgi Equipments Ltd",          sector:"Capital Goods",  base:634,  color:"#FF9500", logo:"🔧",  exchange:"NSE", currency:"₹" },
  { symbol:"FINOLEX",   name:"Finolex Cables Ltd",           sector:"Capital Goods",  base:912,  color:"#5856D6", logo:"🔌",  exchange:"NSE", currency:"₹" },
  { symbol:"RATNAMANI", name:"Ratnamani Metals & Tubes",     sector:"Capital Goods",  base:3234, color:"#FF3B30", logo:"🔩",  exchange:"NSE", currency:"₹" },



  // ── US MARKETS ────────────────────────────────────────────────
  { symbol:"AAPL",  name:"Apple Inc.",             sector:"Technology",      base:189.50,  color:"#007AFF", logo:"🍎", exchange:"NASDAQ", currency:"$" },
  { symbol:"GOOGL", name:"Alphabet Inc.",           sector:"Technology",      base:175.20,  color:"#34C759", logo:"🔍", exchange:"NASDAQ", currency:"$" },
  { symbol:"TSLA",  name:"Tesla Inc.",              sector:"EV/Auto",         base:248.70,  color:"#FF3B30", logo:"⚡", exchange:"NASDAQ", currency:"$" },
  { symbol:"MSFT",  name:"Microsoft Corp.",         sector:"Technology",      base:415.30,  color:"#5856D6", logo:"🪟", exchange:"NASDAQ", currency:"$" },
  { symbol:"AMZN",  name:"Amazon.com Inc.",         sector:"E-Commerce",      base:198.10,  color:"#FF9500", logo:"📦", exchange:"NASDAQ", currency:"$" },
  { symbol:"NVDA",  name:"NVIDIA Corp.",            sector:"Semiconductors",  base:875.40,  color:"#30D158", logo:"🎮", exchange:"NASDAQ", currency:"$" },
  { symbol:"META",  name:"Meta Platforms Inc.",     sector:"Social Media",    base:512.60,  color:"#BF5AF2", logo:"♾️", exchange:"NASDAQ", currency:"$" },
  { symbol:"NFLX",  name:"Netflix Inc.",            sector:"Streaming",       base:628.30,  color:"#FF6B35", logo:"🎬", exchange:"NASDAQ", currency:"$" },
  { symbol:"AMD",   name:"Advanced Micro Devices",  sector:"Semiconductors",  base:178.40,  color:"#FF2D55", logo:"🔴", exchange:"NASDAQ", currency:"$" },
  { symbol:"INTC",  name:"Intel Corporation",       sector:"Semiconductors",  base:42.80,   color:"#64D2FF", logo:"🔵", exchange:"NASDAQ", currency:"$" },
  { symbol:"PYPL",  name:"PayPal Holdings Inc.",    sector:"Fintech",         base:68.50,   color:"#30D158", logo:"💳", exchange:"NASDAQ", currency:"$" },
  { symbol:"UBER",  name:"Uber Technologies Inc.",  sector:"Transport",       base:76.20,   color:"#FF9500", logo:"🚗", exchange:"NYSE",   currency:"$" },
  { symbol:"SPOT",  name:"Spotify Technology SA",   sector:"Streaming",       base:238.10,  color:"#1DB954", logo:"🎵", exchange:"NYSE",   currency:"$" },
  { symbol:"COIN",  name:"Coinbase Global Inc.",    sector:"Crypto/Fintech",  base:195.70,  color:"#0052FF", logo:"🪙", exchange:"NASDAQ", currency:"$" },
  { symbol:"SHOP",  name:"Shopify Inc.",            sector:"E-Commerce",      base:82.40,   color:"#96BF48", logo:"🛒", exchange:"NYSE",   currency:"$" },
  { symbol:"PLTR",  name:"Palantir Technologies",   sector:"AI/Data",         base:22.50,   color:"#FF9F0A", logo:"🧩", exchange:"NYSE",   currency:"$" },
  { symbol:"SNOW",  name:"Snowflake Inc.",          sector:"Cloud",           base:148.20,  color:"#29B5E8", logo:"❄️", exchange:"NYSE",   currency:"$" },
  { symbol:"DDOG",  name:"Datadog Inc.",            sector:"Cloud/Devops",    base:118.70,  color:"#632CA6", logo:"🐕", exchange:"NASDAQ", currency:"$" },
  { symbol:"NET",   name:"Cloudflare Inc.",         sector:"Cybersecurity",   base:92.30,   color:"#F48120", logo:"☁️", exchange:"NYSE",   currency:"$" },
  { symbol:"CRWD",  name:"CrowdStrike Holdings",    sector:"Cybersecurity",   base:264.50,  color:"#E1351E", logo:"🦅", exchange:"NASDAQ", currency:"$" },
  { symbol:"ABNB",  name:"Airbnb Inc.",             sector:"Travel/Tech",     base:142.30,  color:"#FF5A5F", logo:"🏠", exchange:"NASDAQ", currency:"$" },
  { symbol:"ADBE",  name:"Adobe Inc.",              sector:"Software",        base:478.30,  color:"#FF0000", logo:"🎨", exchange:"NASDAQ", currency:"$" },
  { symbol:"CRM",   name:"Salesforce Inc.",         sector:"CRM/SaaS",        base:268.40,  color:"#00A1E0", logo:"☁️", exchange:"NYSE",   currency:"$" },
  { symbol:"NOW",   name:"ServiceNow Inc.",         sector:"SaaS",            base:742.30,  color:"#62D84E", logo:"⚙️", exchange:"NYSE",   currency:"$" },
  { symbol:"RIVN",  name:"Rivian Automotive Inc.",  sector:"EV",              base:14.60,   color:"#47C1BF", logo:"🚙", exchange:"NASDAQ", currency:"$" },
  { symbol:"HOOD",  name:"Robinhood Markets Inc.",  sector:"Fintech",         base:18.40,   color:"#00C805", logo:"🏹", exchange:"NASDAQ", currency:"$" },
  { symbol:"RBLX",  name:"Roblox Corporation",      sector:"Gaming/Metaverse",base:38.70,   color:"#E60012", logo:"🎯", exchange:"NYSE",   currency:"$" },
  { symbol:"U",     name:"Unity Software Inc.",     sector:"Gaming/Graphics", base:22.80,   color:"#FF9500", logo:"🕹️", exchange:"NYSE",   currency:"$" },
  { symbol:"ROKU",  name:"Roku Inc.",               sector:"Streaming HW/SW", base:68.40,   color:"#6C1D45", logo:"📺", exchange:"NASDAQ", currency:"$" },
  { symbol:"TWLO",  name:"Twilio Inc.",             sector:"Communications",  base:62.40,   color:"#F22F46", logo:"📡", exchange:"NYSE",   currency:"$" },
  { symbol:"MDB",   name:"MongoDB Inc.",            sector:"Database/Cloud",  base:372.80,  color:"#00ED64", logo:"🍃", exchange:"NASDAQ", currency:"$" },
  { symbol:"ORCL",  name:"Oracle Corporation",      sector:"Enterprise Tech", base:128.30,  color:"#F80000", logo:"🔴", exchange:"NYSE",   currency:"$" },
  { symbol:"INTU",  name:"Intuit Inc.",             sector:"Fintech/Software",base:612.40,  color:"#365EBF", logo:"💼", exchange:"NASDAQ", currency:"$" },
  { symbol:"WDAY",  name:"Workday Inc.",            sector:"HR/Finance SaaS", base:228.60,  color:"#F5A623", logo:"📋", exchange:"NASDAQ", currency:"$" },
  { symbol:"ZM",    name:"Zoom Video Communications",sector:"SaaS/Video",    base:68.90,   color:"#2D8CFF", logo:"📹", exchange:"NASDAQ", currency:"$" },
  { symbol:"SNAP",  name:"Snap Inc.",               sector:"Social Media",    base:14.30,   color:"#FFD60A", logo:"👻", exchange:"NYSE",   currency:"$" },
  { symbol:"PINS",  name:"Pinterest Inc.",          sector:"Social Media",    base:32.60,   color:"#E60023", logo:"📌", exchange:"NYSE",   currency:"$" },
  { symbol:"NIO",   name:"NIO Inc. ADR",            sector:"EV (China)",      base:6.80,    color:"#00BFFF", logo:"🇨🇳", exchange:"NYSE",   currency:"$" },
  { symbol:"BABA",  name:"Alibaba Group ADR",       sector:"E-Commerce",      base:78.30,   color:"#FF6900", logo:"🛍️", exchange:"NYSE",   currency:"$" },
  { symbol:"JPM",   name:"JPMorgan Chase & Co.",    sector:"Banking",         base:198.40,  color:"#007AFF", logo:"🏦", exchange:"NYSE",   currency:"$" },
  { symbol:"BAC",   name:"Bank of America Corp.",   sector:"Banking",         base:38.20,   color:"#FF3B30", logo:"🏛️", exchange:"NYSE",   currency:"$" },
  { symbol:"GS",    name:"Goldman Sachs Group",     sector:"Investment Bank",  base:478.30,  color:"#30D158", logo:"💹", exchange:"NYSE",   currency:"$" },
  { symbol:"V",     name:"Visa Inc.",               sector:"Payments",        base:278.40,  color:"#1A1F71", logo:"💳", exchange:"NYSE",   currency:"$" },
  { symbol:"MA",    name:"Mastercard Inc.",         sector:"Payments",        base:456.20,  color:"#EB001B", logo:"💲", exchange:"NYSE",   currency:"$" },
  { symbol:"DIS",   name:"The Walt Disney Company", sector:"Entertainment",   base:112.30,  color:"#007AFF", logo:"🏰", exchange:"NYSE",   currency:"$" },
  { symbol:"NFLX2", name:"Netflix Inc. (2)",        sector:"Streaming",       base:628.00,  color:"#E50914", logo:"📽️", exchange:"NASDAQ", currency:"$" },
  { symbol:"PFE",   name:"Pfizer Inc.",             sector:"Pharma",          base:28.40,   color:"#0093D0", logo:"💊", exchange:"NYSE",   currency:"$" },
  { symbol:"JNJ",   name:"Johnson & Johnson",       sector:"Healthcare",      base:156.30,  color:"#CC0000", logo:"🩹", exchange:"NYSE",   currency:"$" },
  { symbol:"XOM",   name:"Exxon Mobil Corp.",       sector:"Energy",          base:104.20,  color:"#FF3B30", logo:"⛽", exchange:"NYSE",   currency:"$" },
  { symbol:"CVX",   name:"Chevron Corporation",     sector:"Energy",          base:156.80,  color:"#007AFF", logo:"🛢️", exchange:"NYSE",   currency:"$" },
];

// ═══════════════════════════════════════════════════════════════
//  IPO DATABASE — India (NSE/BSE) Upcoming + Open + Closed
// ═══════════════════════════════════════════════════════════════
export const IPOS = [
  // ── UPCOMING ─────────────────────────────────────────────────
  {
    id:"ipo1", company:"Ola Electric Mobility Ltd", symbol:"OLAELEC", sector:"EV/Auto",
    status:"upcoming", exchange:"NSE/BSE",
    openDate:"2025-08-15", closeDate:"2025-08-18",
    priceBand:{ low:72, high:76 }, lotSize:195, minInvestment:14820,
    issueSize:"₹6,145 Cr", freshIssue:"₹5,500 Cr", ofs:"₹645 Cr",
    gmp:12, subscriptionTimes:null,
    logo:"🛵", color:"#30D158",
    about:"India's largest EV two-wheeler company. Market leader in electric scooters.",
    pros:["Market leader with 35%+ share","Strong brand recognition","Rapid expansion"],
    cons:["Not yet profitable","Intense competition","High capex requirements"],
    registrar:"Kfin Technologies", lead:"Goldman Sachs, Kotak",
    rating:3,
  },
  {
    id:"ipo2", company:"Swiggy Ltd", symbol:"SWIGGY", sector:"Food Tech",
    status:"upcoming", exchange:"NSE/BSE",
    openDate:"2025-08-22", closeDate:"2025-08-26",
    priceBand:{ low:371, high:390 }, lotSize:38, minInvestment:14820,
    issueSize:"₹11,327 Cr", freshIssue:"₹4,499 Cr", ofs:"₹6,828 Cr",
    gmp:28, subscriptionTimes:null,
    logo:"🍽️", color:"#FF6B35",
    about:"India's leading food delivery and quick commerce platform.",
    pros:["Duopoly market with Zomato","Strong Instamart growth","Large addressable market"],
    cons:["Cash burn continues","Profitability timeline unclear","Competition from Blinkit"],
    registrar:"Link Intime India", lead:"Kotak, JPMorgan, BofA",
    rating:3,
  },
  {
    id:"ipo3", company:"Waaree Energies Ltd", symbol:"WAAREE", sector:"Solar/Renewable",
    status:"upcoming", exchange:"NSE/BSE",
    openDate:"2025-08-28", closeDate:"2025-09-01",
    priceBand:{ low:1427, high:1503 }, lotSize:9, minInvestment:13527,
    issueSize:"₹4,321 Cr", freshIssue:"₹3,600 Cr", ofs:"₹721 Cr",
    gmp:210, subscriptionTimes:null,
    logo:"☀️", color:"#FF9500",
    about:"India's largest solar panel manufacturer with 12 GW annual capacity.",
    pros:["Massive renewable energy tailwind","Govt PLI scheme beneficiary","Export-ready product"],
    cons:["Dependent on imported cells","Margin pressure from competition"],
    registrar:"Kfin Technologies", lead:"ICICI Securities, Axis Capital",
    rating:4,
  },
  {
    id:"ipo4", company:"Mobikwik Systems Ltd", symbol:"MOBIKWIK", sector:"Fintech",
    status:"upcoming", exchange:"NSE/BSE",
    openDate:"2025-09-05", closeDate:"2025-09-09",
    priceBand:{ low:235, high:247 }, lotSize:60, minInvestment:14820,
    issueSize:"₹572 Cr", freshIssue:"₹572 Cr", ofs:"₹0 Cr",
    gmp:18, subscriptionTimes:null,
    logo:"📱", color:"#5856D6",
    about:"Digital payments and financial services platform with 150M+ users.",
    pros:["Profitable for 2 consecutive quarters","Large user base","BNPL growth"],
    cons:["Intense competition (PhonePe, GPay)","Regulatory risk"],
    registrar:"Link Intime India", lead:"SBI Capital, ICICI Securities",
    rating:3,
  },
  {
    id:"ipo5", company:"Emcure Pharmaceuticals Ltd", symbol:"EMCURE", sector:"Pharma",
    status:"upcoming", exchange:"NSE/BSE",
    openDate:"2025-09-12", closeDate:"2025-09-16",
    priceBand:{ low:960, high:1008 }, lotSize:14, minInvestment:14112,
    issueSize:"₹1,952 Cr", freshIssue:"₹800 Cr", ofs:"₹1,152 Cr",
    gmp:95, subscriptionTimes:null,
    logo:"💊", color:"#FF2D55",
    about:"India's 13th largest pharma company, strong in gynaecology & cardiology.",
    pros:["Established brand portfolio","International presence","Consistent profitability"],
    cons:["USFDA compliance risks","Promoter selling stake"],
    registrar:"Kfin Technologies", lead:"Kotak, BofA, Jefferies",
    rating:4,
  },

  // ── OPEN (Currently accepting applications) ───────────────────
  {
    id:"ipo6", company:"Premier Energies Ltd", symbol:"PREMIERENE", sector:"Solar/EPC",
    status:"open", exchange:"NSE/BSE",
    openDate:"2025-08-01", closeDate:"2025-08-05",
    priceBand:{ low:427, high:450 }, lotSize:33, minInvestment:14850,
    issueSize:"₹2,830 Cr", freshIssue:"₹1,291 Cr", ofs:"₹1,539 Cr",
    gmp:85, subscriptionTimes:4.87,
    logo:"⚡", color:"#FFD60A",
    about:"Integrated solar cell and module manufacturer. 2nd largest in India.",
    pros:["Strong order book 6x revenues","Govt policy tailwind","Diversified client base"],
    cons:["Thin margins in EPC","Raw material price volatility"],
    registrar:"Kfin Technologies", lead:"ICICI Securities, Nuvama",
    rating:4,
  },
  {
    id:"ipo7", company:"Bajaj Housing Finance Ltd", symbol:"BAJAJHFL", sector:"Housing Finance",
    status:"open", exchange:"NSE/BSE",
    openDate:"2025-08-02", closeDate:"2025-08-06",
    priceBand:{ low:66, high:70 }, lotSize:214, minInvestment:14980,
    issueSize:"₹6,560 Cr", freshIssue:"₹3,560 Cr", ofs:"₹3,000 Cr",
    gmp:38, subscriptionTimes:7.2,
    logo:"🏠", color:"#007AFF",
    about:"Bajaj Group's housing finance subsidiary. AAA-rated NBFC.",
    pros:["Bajaj brand parentage","Low NPA ratio < 0.3%","Strong growth trajectory"],
    cons:["High competition in HFC space","Interest rate sensitivity"],
    registrar:"KFin Technologies", lead:"Kotak, Goldman, BofA, SBI Cap",
    rating:5,
  },
  {
    id:"ipo8", company:"Orient Technologies Ltd", symbol:"ORIENTTECH", sector:"IT Services",
    status:"open", exchange:"NSE/BSE",
    openDate:"2025-08-02", closeDate:"2025-08-06",
    priceBand:{ low:195, high:206 }, lotSize:72, minInvestment:14832,
    issueSize:"₹214 Cr", freshIssue:"₹120 Cr", ofs:"₹94 Cr",
    gmp:22, subscriptionTimes:11.6,
    logo:"💻", color:"#5856D6",
    about:"IT infrastructure solutions and managed services provider.",
    pros:["SME-to-mainboard transition","Strong profitability","Growing managed services"],
    cons:["Small company, execution risk","Customer concentration"],
    registrar:"Bigshare Services", lead:"Hem Securities",
    rating:3,
  },

  // ── CLOSED / LISTED ───────────────────────────────────────────
  {
    id:"ipo9", company:"Ixigo (Le Travenues Tech)", symbol:"IXIGO", sector:"Travel Tech",
    status:"listed", exchange:"NSE/BSE",
    openDate:"2025-06-10", closeDate:"2025-06-12",
    issuePrice:93, listingPrice:138.10, cmp:187.40,
    priceBand:{ low:88, high:93 }, lotSize:160, minInvestment:14880,
    issueSize:"₹740 Cr", freshIssue:"₹120 Cr", ofs:"₹620 Cr",
    gmp:0, subscriptionTimes:98.34,
    logo:"✈️", color:"#30D158",
    listingGain:48.5, currentGain:101.5,
    about:"India's leading travel platform for Tier 2/3 cities.",
    pros:["Fastest growing travel platform","Unique UPI-focused model","Profitable"],
    cons:["Competition from MakeMyTrip"],
    registrar:"Link Intime", lead:"JM Financial, Axis Capital",
    rating:4,
  },
  {
    id:"ipo10", company:"TBO Tek Ltd", symbol:"TBOTEK", sector:"Travel Tech/SaaS",
    status:"listed", exchange:"NSE/BSE",
    openDate:"2025-05-22", closeDate:"2025-05-24",
    issuePrice:875, listingPrice:1426, cmp:1534,
    priceBand:{ low:875, high:875 }, lotSize:17, minInvestment:14875,
    issueSize:"₹1,550 Cr", freshIssue:"₹400 Cr", ofs:"₹1,150 Cr",
    gmp:0, subscriptionTimes:86.82,
    logo:"🌐", color:"#007AFF",
    listingGain:62.9, currentGain:75.3,
    about:"B2B travel platform connecting hotels and travel agents globally.",
    pros:["Asset-light model","Global presence","Strong GMV growth"],
    cons:["Revenue concentration risk"],
    registrar:"Kfin Technologies", lead:"Goldman Sachs, Kotak",
    rating:5,
  },
  {
    id:"ipo11", company:"Digit Insurance", symbol:"GODIGIT", sector:"InsurTech",
    status:"listed", exchange:"NSE/BSE",
    openDate:"2025-05-15", closeDate:"2025-05-17",
    issuePrice:272, listingPrice:286, cmp:341,
    priceBand:{ low:258, high:272 }, lotSize:54, minInvestment:14688,
    issueSize:"₹2,615 Cr", freshIssue:"₹1,125 Cr", ofs:"₹1,490 Cr",
    gmp:0, subscriptionTimes:13.61,
    logo:"🛡️", color:"#FF9500",
    listingGain:5.1, currentGain:25.4,
    about:"India's fastest growing general insurance company backed by Prem Watsa.",
    pros:["Tech-first insurer","Profitable","Strong brand recall"],
    cons:["High claims ratio in motor segment"],
    registrar:"KFin Technologies", lead:"Axis Capital, IIFL Securities",
    rating:4,
  },
  {
    id:"ipo12", company:"Blackstone (India Hotels)", symbol:"VENTIVE", sector:"Hospitality/REIT",
    status:"listed", exchange:"NSE/BSE",
    openDate:"2025-04-26", closeDate:"2025-04-30",
    issuePrice:643, listingPrice:598, cmp:712,
    priceBand:{ low:610, high:643 }, lotSize:23, minInvestment:14789,
    issueSize:"₹1,600 Cr", freshIssue:"₹1,600 Cr", ofs:"₹0 Cr",
    gmp:0, subscriptionTimes:4.12,
    logo:"🏨", color:"#BF5AF2",
    listingGain:-7.0, currentGain:10.7,
    about:"Premium hospitality assets across India's major metros.",
    pros:["Post-COVID hospitality boom","Prime real estate assets"],
    cons:["Listing below issue price","Economic cycle sensitivity"],
    registrar:"Kfin Technologies", lead:"ICICI Securities, Kotak",
    rating:3,
  },
];

// ── Sector Colors for IPO ──────────────────────────────────────
export const SECTOR_COLORS = {
  "IT": "#007AFF", "Banking": "#30D158", "Pharma": "#FF2D55", "Energy": "#FF6B35",
  "FMCG": "#FF9500", "Auto": "#5856D6", "Finance": "#BF5AF2", "Healthcare": "#64D2FF",
  "EV/Auto": "#30D158", "Food Tech": "#FF6B35", "Solar/Renewable": "#FFD60A",
  "Fintech": "#007AFF", "Travel Tech": "#30D158", "InsurTech": "#FF9500",
};
